#if !canImport(ObjectiveC)
import XCTest

extension HealthAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HealthAPITests = [
        ("testHealth", testHealth),
    ]
}

extension InfluxDB2APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InfluxDB2APITests = [
        ("testCreateApis", testCreateApis),
        ("testCreateInstance", testCreateInstance),
        ("testURLSession", testURLSession),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HealthAPITests.__allTests__HealthAPITests),
        testCase(InfluxDB2APITests.__allTests__InfluxDB2APITests),
    ]
}
#endif
