opt_in_rules:
  - array_init
  - collection_alignment
  - contains_over_first_not_nil
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - empty_string
  - explicit_init
  - explicit_self
  - fatal_error_message
  - first_where
  - implicit_return
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

excluded:
  - Package.swift
  - .build/
